language: python

python:
  - "3.9"

services:
  - docker

before_install:
  - pwd
  - touch ./Django-Movie-Database/.env
  - docker-compose up -d --build

script:
  - docker-compose exec web python manage.py migrate
  - docker-compose exec web python manage.py makemigrations
  - docker-compose exec web python manage.py test && flake8