language: python

python:
  - "3.9"

services:
  - postgresql

before_script:
  - touch Django-Movie-Database/.env

before_install:
  - docker-compose up -d --build

script:
  - docker-compose exec web python manage.py migrate
  - docker-compose exec web python manage.py makemigrations
  - docker-compose exec web python manage.py test && flake8