version: "3.6"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:80
    # command: gunicorn DjangoMovieDatabase.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 80:80
    depends_on:
      - db
    links:
      - db:db
  db:
    image: postgres:12.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
        - ./DjangoMovieDatabase/.env
volumes:
  postgres_data:
