# Generated by Django 3.2.5 on 2021-07-23 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('movie_id',)},
        ),
    ]
